### ISSUE TITLE
Unexpected behavior for recreate_on_update attribute

### ISSUE THREAD

**Issue by AlexVasiukov** [confluentinc/terraform-provider-confluent#235]
Hi,
I cought the behavior that may be classified as a bug.
Example:
Let's deploy 3 version of the same schema subject via terraform (recreate_on_update and hard_delete are set as true):
```
resource "confluent_schema" "avas-schema1-value-1" {
  subject_name       = "avas-schema1-value"
  schema             = file( join("/", [ path.root, "schemas", "avas-schema1-value-v1.json"]) )
  format             = "JSON"
  hard_delete        = true
  recreate_on_update = true
}
resource "confluent_schema" "avas-schema1-value-2" {
  subject_name       = "avas-schema1-value"
  schema             = file( join("/", [ path.root, "schemas", "avas-schema1-value-v2.json"]) )
  format             = "JSON"
  hard_delete        = true
  recreate_on_update = true

  depends_on = [confluent_schema.avas-schema1-value-1]
}
resource "confluent_schema" "avas-schema1-value-3" {
  subject_name       = "avas-schema1-value"
  schema             = file( join("/", [ path.root, "schemas", "avas-schema1-value-v3.json"]) )
  format             = "JSON"
  hard_delete        = true
  recreate_on_update = true

  depends_on = [confluent_schema.avas-schema1-value-2]
}
```
Then, let's change something in the content of the last version and try to redeploy:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # confluent_schema.avas-schema1-value-3 will be updated in-place
  ~ resource "confluent_schema" "avas-schema1-value-3" {
        id                 = "lsrc-5w2rd8/avas-schema1-value/100017"
      ~ schema             = jsonencode(
          ~ {
              ~ properties3          = {
                  ~ myField3 = {
                      ~ description = "Description3" -> "Description33"
                        # (1 unchanged attribute hidden)
                    }
                }
                # (8 unchanged attributes hidden)
            }
        )
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
The schema version is marked for in-place update. The documentation says, that recreate_on_update flag is used 

> to control whether a schema should be recreated on an update

and 

> to manage different schema versions using different resource instances.

So, we can actually manage different schema versions. However, in my opinion, if any of the arguments are changed, the schema version should be marked for recreation in that case.

_Terraform v1.4.4
terraform-provider-confluent_1.39.0_

**Comment by linouk23** [comment]
Thanks for asking @AlexVasiukov! 

Let me try to reproduce the issue. Could you confirm all of these files

* avas-schema1-value-v1.json
* avas-schema1-value-v2.json
* avas-schema1-value-v3.json

aren't the same?

**Comment by linouk23** [comment]
Thanks for sharing the schema definitions! I can confirm that I've managed to reproduce an issue and it looks like a bug to me 👍

**Comment by linouk23** [comment]
Actually I took another look and this issue seems to be a duplicate of #218.

More specifically, if you actually run `terraform apply` you'll see an error:
```
confluent_schema.avas-schema1-value-3: Modifying... [id=lsrc-d9qkjo/avas-schema1-value/100003]
╷
│ Error: error updating Schema "lsrc-111111/avas-schema1-value/100003": reimport the current resource instance and set recreate_on_update = false to evolve a schema using the same resource instance.
│ In this case, on an update resource instance will reference the updated (latest) schema by overriding schema_identifier, schema and version attributes and the old schema will be orphaned.
```
and the reason you can see `Plan: 0 to add, 1 to change, 0 to destroy.` is that in order to show `Plan: 1 to add, 0 to change, 1 to destroy.` we have to mark `schema` attribute as `ForceNew: true` (see [the docs](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#forcenew), [code pointer](https://github.com/confluentinc/terraform-provider-confluent-internal/blob/master/internal/provider/resource_schema.go#L97-L103)) but it can't be applied since we don't want to recreate a schema if `recreate_on_update` is set to `false`.

Let me know whether it helps! We'd be happy to update the docs if you could suggest a better wording too, thanks!

cc @AlexVasiukov

**Comment by AlexVasiukov** [comment]
@linouk23 just thinking out loud. Perhaps it's possible to define two `schema` attributes  (e.x. "schema" and "schema_def"), one of which will have `ForceNew` field as `false` and other will have `ForceNew` field as `true`. The first one will be used if `recreate_on_update` is set to `false` and the second one will be used in case when `recreate_on_update` is set to `true`.

**Comment by linouk23** [comment]
It might be an interesting solution! Unfortunately we have already marked `confluent_schema` resource as Generally Available: 
![image](https://user-images.githubusercontent.com/5459870/234037283-028ca868-c78b-4db5-b642-38a927dc5ce9.png)
meaning 

> Generally Available (GA) – Will not change at short notice. Recommended for production usage. Officially supported by Confluent for non-production and production usage.

so we'd like to avoid any breaking changes.

But we'll take a note and consider this approach for the next major version of TF Provider for Confluent.

Alternatively, we could also move this check into `CustomizeDiff` [attribute](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/customizing-differences) which allows to move these checks from `terraform apply` to `terraform plan` stage.

**Comment by linouk23** [comment]
update: @AlexVasiukov the fix will be released in a new version of TF Provider, thanks for reporting the bug!

**Comment by linouk23** [comment]
The issue has been resolved in [version 1.46.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1460-june-23-2023), which has been released on June 26th.

cc @AlexVasiukov

**Comment by AlexVasiukov** [comment]
> The issue has been resolved in [version 1.46.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1460-june-23-2023), which has been released on June 26th.
> 
> cc @AlexVasiukov

@linouk23 , thanks for the feedback!
I just tested the current release (1.47) and, as I understood correctly, the issue wasn't completely resolved, but was patched to move the current check from `terraform apply` to `terraform plan` (as was suggested in #218).
So, now we have an error while trying to plan some incompatible change in schema version with `recreate_on_update` flag set to true:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: error updating Schema "lsrc-3nwd2j/avas-schema1-value/100003": reimport the current resource instance and set recreate_on_update = false to evolve a schema using the same resource instance.
│ In this case, on an update resource instance will reference the updated (latest) schema by overriding schema_identifier, schema and version attributes and the old schema will be orphaned.
│
│   with confluent_schema.avas-schema1-value-3,
│   on main.tf line 164, in resource "confluent_schema" "avas-schema1-value-3":
│  164: resource "confluent_schema" "avas-schema1-value-3" {
```
I doubt that this behavior is most expected. To my mind, the expected behavior is to recreate the current resource by deleting it and creating again and re-point `schema_identifier` to the new resource (and the old schema will be orphaned, just like it was mentioned in the error message above). I understand, that this behavior couldn't be done for the current major version. Perhaps, it's possible to redone this behavior in the next major, isn't it?
