### ISSUE TITLE
API key creation for dedicated clusters fails if terraform can't access cluster

### ISSUE THREAD

**Issue by west-david** [confluentinc/terraform-provider-confluent#25]
Scenario: terraform running from a CICD pipeline provisioning API key resources fails with this error:

```
Error: error waiting for Kafka API Key "[REDACTED]" to sync: error listing Kafka Topics using Kafka API Key "[REDACTED]": Get "[https://[REDACTED]/kafka/v3/clusters/[REDACTED]/topics](https://[REDACTED]/kafka/v3/clusters/[REDACTED]/topics)": GET [https://[REDACTED]/kafka/v3/clusters/[REDACTED]/topics](https://[REDACTED]/kafka/v3/clusters/[REDACTED]/topics) giving up after 5 attempt(s): Get "[https://[REDACTED]/kafka/v3/clusters/[REDACTED]/topics](https://[REDACTED]/kafka/v3/clusters/[REDACTED/topics)": dial tcp [REDACTED]:443: i/o timeout
```

Subsequent terraform runs will attempt to re-create the API keys, which will fail again.

The API keys are created and applied to the clusters, but the provider assumes that it has connectivity to the cluster and this is not necessarily the case - dedicated clusters using VPC peering may not be accessible from the node running the CI pipeline. It should be possible to provision resources via the confluent cloud API *without* also having access to the resource (cluster). Terraform provider should be able to provision all resources via the confluent cloud public API endpoint without requiring direct access to private kafka cluster endpoints.  

Suggestion: validate API key creation via confluent cloud API instead of against the actual cluster endpoint *OR* add optional `confluent_api_key` resource attribute disabling this test

**Comment by linouk23** [comment]
👋 @west-david thanks for opening an issue!

I think your concern totally makes sense and we'll implement your 2nd suggestion in one of our future releases!

**Comment by linouk23** [comment]
On a somewhat related note, could you share with us how you are going to create topic / ACLs using created Kafka API Key given the fact the Kafka cluster won't be reachable from the CI pipeline? cc @west-david

**Comment by west-david** [comment]
@linouk23 ahhhhhh good point... 🤦 definitely overlooked that. As awesome as it would be to have the ability to terraform everything end to end over the public cloud API endpoint I definitely acknowledge that there are some limitations. I suppose we will have to re-work some of the CI to run "inside" the cloud environments that have access to the clusters.

**Comment by ericdalling** [comment]
I'm running into the same error when creating a `confluent_api_key` with a dedicated cluster over AWS Private Link. We have added the private link to the VPC of our CI pipeline but still get the same error. I'm wondering if Terraform is using the wrong URL to communicate with the cluster, when using private link. It looks like it is using the REST endpoint vs the private link's DNS domain. Is that the right behavior?

**Comment by linouk23** [comment]
@ericdalling that's very surprising, are you using one of our example PL [configurations](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/dedicated-privatelink-aws-kafka-rbac) by any chance?

**Comment by ericdalling** [comment]
@linouk23 thanks for sharing that example, I hadn't seen that before. Most of what we are doing looks the same, except for the Route53 resources. So will this only work if we create the Route53 private hosted zone to override the URLs for the REST endpoints? I'm not sure that is the best approach. It seems like it would be better to have an optional variable at the resources that need to connect to the cluster to override the cluster's URL. This way we could pass in the private links URL and not need to use Route53. I'm not sure we will get approved to setup Route53 in our build team's AWS account.

**Comment by linouk23** [comment]
@ericdalling the example I sent corresponds to our [tutorial](https://docs.confluent.io/cloud/current/networking/private-links/aws-privatelink.html#set-up-dns-records-to-use-aws-vpc-endpoints):

> Any DNS provider can be used - AWS Route53 (used in this example) is not required. Any DNS provider that can ensure DNS is routed as follows is acceptable.

> It seems like it would be better to have an optional variable at the resources that need to connect to the cluster to override the cluster's URL. This way we could pass in the private links URL and not need to use Route53. I'm not sure we will get approved to setup Route53 in our build team's AWS account.

That sounds interesting, it'd be great if could share this config in a PR or something.

Did you include `depends_on` block for your `api_key` resource like [this](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/dedicated-privatelink-aws-kafka-rbac/main.tf#L95)?
```
# The goal is to ensure that
  # 1. confluent_role_binding.app-manager-kafka-cluster-admin is created before
  # confluent_api_key.app-manager-kafka-api-key is used to create instances of
  # confluent_kafka_topic resource.
  # 2. Kafka connectivity through AWS PrivateLink is setup.
  depends_on = [
    confluent_role_binding.app-manager-kafka-cluster-admin,

    confluent_private_link_access.aws,
    aws_vpc_endpoint.privatelink,
    aws_route53_record.privatelink,
    aws_route53_record.privatelink-zonal,
  ]
```

**Comment by ericdalling** [comment]
@linouk23 in the [tutorial](https://docs.confluent.io/cloud/current/networking/private-links/aws-privatelink.html#set-up-dns-records-to-use-aws-vpc-endpoints) that you shared, it says 

> Paste Confluent Cloud DNS into Domain Name. This can be found in the Confluent Cloud Console.

Is that referring the the Private Link's DNS Domain? If so, it doesn't appear that the DNS Domain is available as an output variable on the `confluent_network` resource. As a future enhancement, would it be possible to add the DNS Domain as an output variable for the `confluent_network` resource?

**Comment by linouk23** [comment]
> As a future enhancement, would it be possible to add the DNS Domain as an output variable for the confluent_network resource?

That's a great idea, https://github.com/confluentinc/terraform-provider-confluent/issues/40

**Comment by linouk23** [comment]
@ericdalling we're happy to let you know we've just released `0.9.0` [version](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#090-may-25-2022) of TF Provider that includes `dns_domain` and `zonal_subdomains` computed attributes for `confluent_network` resource.

**Comment by maheshbhole** [comment]
Hello,
I am still getting above error.
Is this check of validation of API key against actual clsuter disabled ? 
I tried another work around of giving wait time but that also does not work?

**Comment by linouk23** [comment]
@maheshbhole see https://github.com/confluentinc/terraform-provider-confluent/issues/51#issuecomment-1159592017

**Comment by west-david** [comment]
thanks @linouk23 🙌
