### ISSUE TITLE
error creating Tag Binding / Business Metadata Binding 404

### ISSUE THREAD

**Issue by marconak-itera** [confluentinc/terraform-provider-confluent#282]
Hello,

we are using new `confluent_business_metadata_binding` and `confluent_tag_binding` and we are adding the **tags** and **business metadata** on **topic** and **schema**. 

The common case for us is create:

- topic
- schema
- tags
- business metadata

in one run. The topics/schema contains usually 3-4 tags, 1-2  business metadata.

But when are running the `terraform` in some case we are getting error:

``
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.....confluent_business_metadata_binding.business_metadata_topic_entity_type["Team"],
│ provider "provider[\"registry.terraform.io/confluentinc/confluent\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
``

``
Error: error creating Tag Binding 404 Not Found
``
``
Error creating Business Metadata Binding 404 Not Found
``

When we rerun terraform again, in some cases it will finish successfully, but in other case there is error regarding the tags or metadata that already exists.

``
error creating Business Metadata Binding ".../Team/....:topic/kafka_topic": Business-metadata attribute already exists in entity: ....
``

We have to manually removed tags/metadata to able run the terraform successful.

Configuration looks like something like this:

```tf
# create tags for open on topic
resource "confluent_tag_binding" "open-topic-tagging" {
  schema_registry_cluster {
    id = confluent_schema_registry_cluster.main.id
  }
  rest_endpoint = confluent_schema_registry_cluster.main.rest_endpoint
  credentials {
    key    = confluent_api_key.env-manager-schema-registry-api-key.id
    secret = confluent_api_key.env-manager-schema-registry-api-key.secret
  }

  tag_name = confluent_tag.open.name
  entity_name = "${confluent_schema_registry_cluster.main.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}"
  entity_type = local.topic_entity_type
}

# create tags for private on topic
resource "confluent_tag_binding" "private-topic-tagging" {
  schema_registry_cluster {
    id = confluent_schema_registry_cluster.main.id
  }
  rest_endpoint = confluent_schema_registry_cluster.main.rest_endpoint
  credentials {
    key    = confluent_api_key.env-manager-schema-registry-api-key.id
    secret = confluent_api_key.env-manager-schema-registry-api-key.secret
  }

  tag_name = confluent_tag.private.name
  entity_name = "${confluent_schema_registry_cluster.main.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}"
  entity_type = local.topic_entity_type
}

# create tags for open on schema
resource "confluent_tag_binding" "open-schema-tagging" {
  schema_registry_cluster {
    id = confluent_schema_registry_cluster.main.id
  }
  rest_endpoint = confluent_schema_registry_cluster.main.rest_endpoint
  credentials {
    key    = confluent_api_key.env-manager-schema-registry-api-key.id
    secret = confluent_api_key.env-manager-schema-registry-api-key.secret
  }

  tag_name = confluent_tag.open.name
  entity_name = "${confluent_schema_registry_cluster.main.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}"
  entity_type = local.topic_entity_type
}

# create tags for private on schema
resource "confluent_tag_binding" "private-schema-tagging" {
  schema_registry_cluster {
    id = confluent_schema_registry_cluster.main.id
  }
  rest_endpoint = confluent_schema_registry_cluster.main.rest_endpoint
  credentials {
    key    = confluent_api_key.env-manager-schema-registry-api-key.id
    secret = confluent_api_key.env-manager-schema-registry-api-key.secret
  }

  tag_name = confluent_tag.private.name
  entity_name = "${confluent_schema_registry_cluster.main.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}"
  entity_type = local.schema_entity_type
}

# create business metadata for team on topic
resource "confluent_business_metadata_binding" "topic-bm-binding-team" {
  schema_registry_cluster {
    id = confluent_schema_registry_cluster.main.id
  }
  rest_endpoint = confluent_schema_registry_cluster.main.rest_endpoint
  credentials {
    key    = confluent_api_key.env-manager-schema-registry-api-key.id
    secret = confluent_api_key.env-manager-schema-registry-api-key.secret
  }

  business_metadata_name = confluent_business_metadata.main.name
  entity_name = "${confluent_schema_registry_cluster.main.id}:${confluent_kafka_cluster.basic.id}:${confluent_kafka_topic.purchase.topic_name}"
  entity_type = local.topic_entity_type
  attributes = {
    "team" = "Sam"
  }
}

# create business metadata for team on schema
resource "confluent_business_metadata_binding" "schema-bm-binding-team" {
  schema_registry_cluster {
    id = confluent_schema_registry_cluster.main.id
  }
  rest_endpoint = confluent_schema_registry_cluster.main.rest_endpoint
  credentials {
    key    = confluent_api_key.env-manager-schema-registry-api-key.id
    secret = confluent_api_key.env-manager-schema-registry-api-key.secret
  }

  business_metadata_name = confluent_business_metadata.main.name
  entity_name = "${confluent_schema_registry_cluster.main.id}:.:${confluent_schema.purchase.schema_identifier}"
  entity_type = local.schema_entity_type
  attributes = {
    "team" = "Sam"
  }
}

locals {
  topic_entity_type = "kafka_topic"
  schema_entity_type = "sr_schema"
  record_entity_type = "sr_record"
}
```

The version

```tf
    confluent = {
      source  = "confluentinc/confluent"
      version = "~> 1.48.0"
    }
```

**Comment by linouk23** [comment]
Thanks for creating an issue @marconak-itera! https://github.com/confluentinc/terraform-provider-confluent/issues/253 looks relevant to this issue, we'll take a look at it shortly.

**Comment by linouk23** [comment]
This was fixed in `1.49.0`: https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1490-july-17-2023

@marconak-itera could you try again and see whether you can reproduce the issue? Thanks!

**Comment by marconak-itera** [comment]
It is more stable as before. Most of terraform runs finished successfully. 

But there was run which finished with error, we were creating the topic, schema, tags and metadata for topic and schema in one run:

logs:
```tf
module.custom_resource_name_topic.confluent_kafka_topic.main: Creating...
module.custom_resource_name_schema.confluent_schema.main: Creating...
module.custom_resource_name_topic.confluent_kafka_topic.main: Still creating... [10s elapsed]
module.custom_resource_name_schema.confluent_schema.main: Still creating... [10s elapsed]
module.custom_resource_name_topic.confluent_kafka_topic.main: Creation complete after 11s [id=cluster-id/topic-name]

module.custom_resource_name_topic.confluent_tag_binding.tag_topic_entity_type["open"]: Creating...
module.custom_resource_name_topic.confluent_tag_binding.tag_topic_entity_type["regular"]: Creating...
module.custom_resource_name_topic.confluent_tag_binding.tag_topic_entity_type["s"]: Creating...
module.custom_resource_name_topic.confluent_tag_binding.tag_topic_entity_type["no"]: Creating...
module.custom_resource_name_topic.confluent_tag_binding.tag_topic_entity_type["cdc"]: Creating...
module.custom_resource_name_topic.confluent_business_metadata_binding.business_metadata_topic_entity_type["Team"]: Creating...

module.custom_resource_name_schema.confluent_schema.main: Creation complete after 11s [id=cluster-id/topic-name-value/latest]
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["cdc"]: Creating...
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["regular"]: Creating...
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["open"]: Creating...
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["no"]: Creating...
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["s"]: Creating...

module.custom_resource_name_schema.confluent_business_metadata_binding.business_metadata_schema_entity_type["Team"]: Creating...
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["cdc"]: Creation complete after 6s [id=cluster-id/cdc/cluster-id:.:id/sr_schema]
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["open"]: Creation complete after 6s [id=cluster-id/open/cluster-id:.:id/sr_schema]
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["no"]: Creation complete after 6s [id=cluster-id/gfno/cluster-id:.:id/sr_schema]
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["s"]: Creation complete after 6s [id=cluster-id/s2000/cluster-id:.:id/sr_schema]
module.custom_resource_name_schema.confluent_tag_binding.tag_schema_entity_type["regular"]: Creation complete after 7s [id=cluster-id/regular_retention/cluster-id:.:id/sr_schema]
module.custom_resource_name_schema.confluent_business_metadata_binding.business_metadata_schema_entity_type["Team"]: Creation complete after 8s [id=cluster-id/Team/cluster-id:.:id/sr_schema]
```

which failed on creating tags and metadata for topic, the tags and metadata for schema were created:

```
Error: error creating Tag Binding 404 Not Found
│
│   with module.custom_resource_name_topic.confluent_tag_binding.tag_topic_entity_type["s"]


Error: error creating Tag Binding 404 Not Found
│
│   with module.custom_resource_name_topic.confluent_tag_binding.tag_topic_entity_type["regular"],

│ Error: error creating Business Metadata Binding 404 Not Found
│
│   with module.custom_resource_name_topic.confluent_business_metadata_binding.business_metadata_topic_entity_type["Team"],
```

**Comment by linouk23** [comment]
@marconak-itera thanks for testing it out!

Could you try new version 1.50.0: https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1500-july-21-2023 too when you've got a moment? We've increased timeouts so it should be even more reliable. Thanks!

**Comment by chawleejay** [comment]
im still receiving 404 errors on tag binding creation when using version 1.50.0 @linouk23

**Comment by zhenli00** [comment]
Hi @chawleejay By any chance do you still remember how long it took to  complete all provisioning after you hit 404?
We think it's due to some underlying API issues instead of terraform itself.

**Comment by chawleejay** [comment]
its happening instantly after the creation of topic

**Comment by linouk23** [comment]
@chawleejay could you try `1.51.0`? We believe we finally identified the issue 😁 

Thank you for bearing with us!

**Comment by linouk23** [comment]
cc @marconak-itera

**Comment by chawleejay** [comment]
@linouk23 darn! tried `1.51.0` and still receiving the same 404 error. Sucessfully creates topic and errors on tag creation on first run. then second run will only have tag creation and second run succeeds

**Comment by chawleejay** [comment]
`confluent-test  Initializing the backend...
confluent-test  Initializing provider plugins...
confluent-test  - Reusing previous version of confluentinc/confluent from the dependency lock file
confluent-test  - Using previously-installed confluentinc/confluent v1.51.0
confluent-test  Terraform has been successfully initialized!
                
                You may now begin working with Terraform. Try running "terraform plan" to see
                any changes that are required for your infrastructure. All Terraform commands
                should now work.

                If you ever set or change modules or backend configuration for Terraform,
                rerun this command to reinitialize your working directory. If you forget, other
                commands will detect it and remind you to do so if necessary.
confluent-test  Terraform used the selected providers to generate the following execution plan.
                Resource actions are indicated with the following symbols:
confluent-test  + create

                Terraform will perform the following actions:

                  # confluent_kafka_topic.tp1 (tp1) will be created
                  + resource "confluent_kafka_topic" "tp1" {
                      + config           = {
                          + "cleanup.policy"    = "delete"
                          + "max.message.bytes" = "2097164"
                          + "retention.ms"      = "86400000"
                        }
                      + id               = (known after apply)
                      + partitions_count = 2
                      + topic_name       = "public.iac.tag.test"
                    }

                  # confluent_tag_binding.tp1-Public (tp1-Public) will be created
                  + resource "confluent_tag_binding" "tp1-Public" {
                      + entity_name = "<removed cluster id's>:public.iac.tag.test"
                      + entity_type = "kafka_topic"
                      + id          = (known after apply)
                      + tag_name    = "Public"
                    }

                Plan: 2 to add, 0 to change, 0 to destroy.
confluent-test  
                Do you want to perform these actions?
                  Terraform will perform the actions described above.
                  Only 'yes' will be accepted to approve.
confluent-test  Enter a value: yes
confluent-test  confluent_kafka_topic.tp1 (tp1): Creating...
confluent-test  confluent_kafka_topic.tp1 (tp1): Still creating... [10s elapsed]
confluent-test  confluent_kafka_topic.tp1 (tp1): Creation complete after 11s [id=<removed cluster id>/public.iac.tag.test]
confluent-test  confluent_tag_binding.tp1-Public (tp1-Public): Creating...
confluent-test  ╷
                │ Error: error creating Tag Binding 404 Not Found
                │ 
                │   with confluent_tag_binding.tp1-Public (tp1-Public),
                │   on cdk.tf.json line 46, in resource.confluent_tag_binding.tp1-Public (tp1-Public):
                │   46:       }
                │ 
                ╵


0 Stacks deploying     1 Stack done     0 Stacks waiting
Invoking Terraform CLI failed with exit code 1`

**Comment by zhenli00** [comment]
> ` confluent-test Initializing the backend... confluent-test Initializing provider plugins... confluent-test - Reusing previous version of confluentinc/confluent from the dependency lock file confluent-test - Using previously-installed confluentinc/confluent v1.51.0 confluent-test Terraform has been successfully initialized!
> 
> ```
>             You may now begin working with Terraform. Try running "terraform plan" to see
>             any changes that are required for your infrastructure. All Terraform commands
>             should now work.
> 
>             If you ever set or change modules or backend configuration for Terraform,
>             rerun this command to reinitialize your working directory. If you forget, other
>             commands will detect it and remind you to do so if necessary.
> ```
> 
> confluent-test Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols: confluent-test + create
> 
> ```
>             Terraform will perform the following actions:
> 
>               # confluent_kafka_topic.tp1 (tp1) will be created
>               + resource "confluent_kafka_topic" "tp1" {
>                   + config           = {
>                       + "cleanup.policy"    = "delete"
>                       + "max.message.bytes" = "2097164"
>                       + "retention.ms"      = "86400000"
>                     }
>                   + id               = (known after apply)
>                   + partitions_count = 2
>                   + topic_name       = "public.iac.tag.test"
>                 }
> 
>               # confluent_tag_binding.tp1-Public (tp1-Public) will be created
>               + resource "confluent_tag_binding" "tp1-Public" {
>                   + entity_name = "<removed cluster id's>:public.iac.tag.test"
>                   + entity_type = "kafka_topic"
>                   + id          = (known after apply)
>                   + tag_name    = "Public"
>                 }
> 
>             Plan: 2 to add, 0 to change, 0 to destroy.
> ```
> 
> confluent-test Do you want to perform these actions? Terraform will perform the actions described above. Only 'yes' will be accepted to approve. confluent-test Enter a value: yes confluent-test confluent_kafka_topic.tp1 (tp1): Creating... confluent-test confluent_kafka_topic.tp1 (tp1): Still creating... [10s elapsed] confluent-test confluent_kafka_topic.tp1 (tp1): Creation complete after 11s [id=/public.iac.tag.test] confluent-test confluent_tag_binding.tp1-Public (tp1-Public): Creating... confluent-test ╷ │ Error: error creating Tag Binding 404 Not Found │ │ with confluent_tag_binding.tp1-Public (tp1-Public), │ on cdk.tf.json line 46, in resource.confluent_tag_binding.tp1-Public (tp1-Public): │ 46: } │ ╵
> 
> 0 Stacks deploying 1 Stack done 0 Stacks waiting Invoking Terraform CLI failed with exit code 1 `

@chawleejay When you specify the topic in entity_name, did you reference the topic resource or just hard code the topic name?

**Comment by dandrivetime** [comment]
@zhenli00 - It's a reference. (@chawleejay and I work together). It seems like what's happening is the schema registry is not yet "aware" of the newly created topic (even though terraform receives the "Creation complete" message). If the same code is executed a 2nd time, the tag binding completes without error.

This doesn't occur on adding a tag to an existing topic, which supports the theory - though it's just a guess.

**Comment by zhenli00** [comment]
@dandrivetime Thanks for sharing. This is our assumption as well, we have added a 5s sleep before creating the binding, the other thing we can do is to increase the sleep time, we will contact our SR as well to investigate.

**Comment by marconak-itera** [comment]
I also can confirm - after topic creation in same run - the adding tags/metadata fails also on version 1.51.0

**Comment by dandrivetime** [comment]
@linouk23 @zhenli00 - can you reproduce this in your local testing? Maybe try pushing the sleep to 30 sec or something just to prove it's a timing issue? Slowly back it down to get the error again?

**Comment by linouk23** [comment]
@dandrivetime @marconak-itera could you confirm that your SR and Kafka clusters are in the same environment?

We'll add more descriptive errors in the next version of TF provider but basically we can see:
```
confluent_tag_binding.pii-topic-tagging: Still creating... [3m0s elapsed]
╷
│ Error: error creating Tag Binding 404 Not Found: Instance kafka_topic with unique attribute {qualifiedName=lsrc-23106o:lkc-m80307:topickostya123} does not exist
```

when SR and Kafka clusters are in different environments (they _should_ be in the same environment AFAIK).

Could you also share a type of your Kafka cluster? Even if I set sleep time to 1 second, I can't really reproduce 404 🤔 

even when I force a topic to be created right before a tag binding:
```
resource "confluent_tag" "pii" {
  name = "test123"
  description = "Personally identifiable information"
}

resource "confluent_kafka_topic" "test" {
  topic_name = "topickostya123"
  depends_on = [
    confluent_tag.pii
  ]
}

resource "confluent_tag_binding" "pii-topic-tagging" {
  tag_name = confluent_tag.pii.name
  entity_name = "lsrc-23106o:lkc-3ndj9m:${confluent_kafka_topic.test.topic_name}"
  entity_type = "kafka_topic"
}
```

**Comment by dandrivetime** [comment]
@linouk23 - yes the SR's are in the same environment. We have a test and prod env. They're both type: `dedicated` (running in azure). 

I'm not sure why this is so different for us, vs. your local testing! Even if I immediately ( as fast as I can up arrow and press the enter key) run the code again, it will work the 2nd time.

This suggests there's not really anything wrong with the inputs/resource setup in our code, but rather something going on with coordination we're not able to see.

**Comment by dandrivetime** [comment]
@linouk23 @zhenli00 - I forced in a timer for 1 minute after the topic is created. This seems to prove out there's a timing issue behind the scenes. 

```
confluent-test  confluent_kafka_topic.tp1 (tp1): Creating...
confluent-test  confluent_kafka_topic.tp1 (tp1): Still creating... [10s elapsed]
confluent-test  confluent_kafka_topic.tp1 (tp1): Creation complete after 12s [id=****/public.iac.tag.timing.test]
confluent-test  time_sleep.sleep-tp1 (sleep-tp1): Creating...
confluent-test  time_sleep.sleep-tp1 (sleep-tp1): Still creating... [10s elapsed]
confluent-test  time_sleep.sleep-tp1 (sleep-tp1): Still creating... [20s elapsed]
confluent-test  time_sleep.sleep-tp1 (sleep-tp1): Still creating... [30s elapsed]
confluent-test  time_sleep.sleep-tp1 (sleep-tp1): Still creating... [40s elapsed]
confluent-test  time_sleep.sleep-tp1 (sleep-tp1): Still creating... [50s elapsed]
confluent-test  time_sleep.sleep-tp1 (sleep-tp1): Creation complete after 1m0s [id=2023-08-22T00:18:49Z]
confluent-test  confluent_tag_binding.tp1-Public (tp1-Public): Creating...
confluent-test  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [10s elapsed]
confluent-test  confluent_tag_binding.tp1-Public (tp1-Public): Creation complete after 11s [id=****/Public/****:****:public.iac.tag.timing.test/kafka_topic]
confluent-test  Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Comment by linouk23** [comment]
@dandrivetime we just released a new version of TF Provider (1.52.0) where we increased a timer to a minute! Let us know if that mitigates the issue.

**Comment by marconak-itera** [comment]
Hello, we updated the version, it still fails it from time to time

errors:
```
Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to confluent_tag_binding ...,
│ provider "provider[\"registry.terraform.io/confluentinc/confluent\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to business_metadata_schema_entity_type ... ,
│ provider "provider[\"registry.terraform.io/confluentinc/confluent\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

after rerun 

```
 Error: error creating Tag Binding ... already is associated with classification tag


```│ Error: error creating Business Metadata Binding ... : Business-metadata attribute already exists in entity: ...

**Comment by HSA72** [comment]
Hi @linouk23 can you look at this bug? 

We are using `1.56.0` and this happens too often. It is very time-consuming for the central Kafka enabling team to manually delete tags and business metadata in the Confluent cloud UI for other teams (that do/should not have access to delete in the UI) to be able to run the whole TF-apply.

**Comment by linouk23** [comment]
@marconak-itera @HSA72 @dandrivetime we've just merged a new fix internally (added timeout in a _different_ method so hopefully it'll mitigate the issue) that we'll include in our next release of TF Provider that should happen early in January.

**Comment by linouk23** [comment]
@marconak-itera @HSA72 @dandrivetime

Update: we

> Added a client side fix for "error creating Tag Binding / Business Metadata Binding 404" issue (https://github.com/confluentinc/terraform-provider-confluent/issues/282).

in our latest [1.57.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1570-january-4-2023) version of TF Provider.

Thanks for waiting and let us know if you run into any issues when using the latest [1.57.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1570-january-4-2023) version of TF Provider.

**Comment by linouk23** [comment]
@marconak-itera @HSA72 @dandrivetime we've just merged release a new [1.58.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1580-january-11-2023) version of TF Provider with increased timeout that should help to fix 

```
│ provider "provider[\"registry.terraform.io/confluentinc/confluent\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

Let us know if the issue persists, thanks!

**Comment by dandrivetime** [comment]
@linouk23 - I upgraded to the 1.58 version. Looks like it works (note I only tested once :) ) - 

`                Plan: 5 to add, 0 to change, 0 to destroy.
confluent-prod  confluent_kafka_acl.acl4 (acl4): Creating...
                confluent_kafka_topic.tp1 (tp1): Creating...
confluent-prod  confluent_kafka_topic.tp1 (tp1): Still creating... [10s elapsed]
confluent-prod  confluent_kafka_acl.acl4 (acl4): Still creating... [10s elapsed]
confluent-prod  confluent_kafka_acl.acl4 (acl4): Creation complete after 11s [id=xxxx/GROUP#iac-group-test#LITERAL#User:xxxx#*#READ#ALLOW]
confluent-prod  confluent_kafka_topic.tp1 (tp1): Creation complete after 11s [id=xxxx/public.iac.devops.test]
confluent-prod  confluent_kafka_acl.acl1 (acl1): Creating...
                confluent_tag_binding.tp1-Public (tp1-Public): Creating...
                confluent_kafka_acl.acl2 (acl2): Creating...
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [10s elapsed]
                confluent_kafka_acl.acl2 (acl2): Still creating... [10s elapsed]
                confluent_kafka_acl.acl1 (acl1): Still creating... [10s elapsed]
confluent-prod  confluent_kafka_acl.acl2 (acl2): Creation complete after 10s [id=xxxx/TOPIC#public.iac.devops.test#LITERAL#User:xxxx#*#READ#ALLOW]
confluent-prod  confluent_kafka_acl.acl1 (acl1): Creation complete after 10s [id=xxxx/TOPIC#public.iac.devops.test#LITERAL#User:xxxx#*#WRITE#ALLOW]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [20s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [30s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [40s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [50s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [1m0s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [1m10s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [1m20s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [1m30s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [1m40s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [1m50s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Still creating... [2m0s elapsed]
confluent-prod  confluent_tag_binding.tp1-Public (tp1-Public): Creation complete after 2m1s [id=xxxx/Public/lsrc-xxxx:xxxx:public.iac.devops.test/kafka_topic]
confluent-prod  Apply complete! Resources: 5 added, 0 changed, 0 destroyed.`

**Comment by linouk23** [comment]
Nice!

We realized we updated timeouts for `confluent_tag_binding` but forgot to update timeouts for `confluent_business_metadata_binding` so we'll be making another quick update that might help 👌

**Comment by linouk23** [comment]
update: thanks for waiting, we released `1.59.0` that updates timeouts for `confluent_business_metadata_binding` resource too which should resolve:
```
confluent_business_metadata_binding.business_metadata_topic_entity_type["Team"], │ provider "provider[\"registry.terraform.io/confluentinc/confluent\"]" │ produced an unexpected new value: Root resource was present, but now │ absent. │
```
Thanks!
